spring:
  main:
    log-startup-info: OFF

vending:
  machine:
    products: Walkers Cheese & Onion,Walkers Ready Salted,Twix Bar,Cadbury Twirl
    prices: 0.30,0.30,1.2,1.5


logging:
  level:
    root: INFO
    com.oracle.vending.api: DEBUG